# Generated by Django 4.0.4 on 2022-05-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190310_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='persons',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='taste',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='vat',
            field=models.CharField(max_length=120),
        ),
    ]
